
build-docker:
	docker build -t decodeproject/chainspace-java-2-nodes:SNAPSHOT .

run-docker:
	docker run -p 5000:5000 decodeproject/chainspace-java-2-nodes:SNAPSHOT

ssh-docker:
	echo "docker exec -t -i <container-id> /bin/bash"

bash-docker:
	docker run -t -i decodeproject/chainspace-java-2-nodes:SNAPSHOT /bin/bash




